EXEC SP_AltaEmpleado 'PAMELA', 'ARIZAGA', 'GONZALEZ', 'Administración', 'pamm.gla@gmail.com', '01/08/1997',NULL;
EXEC SP_AltaEmpleado 'GIOVANNI', 'ALMAZAN', 'GARCIA', 'Sistemas', 'gio.almazan.garcia@gmail.com', '02/08/1997',NULL;
EXEC SP_AltaEmpleado 'ROSA ELENA', 'ANAYA', 'BADILLO', 'Mecatrónica', 'rosa.elena1996@hotmail.com', '03/08/1997',NULL;
EXEC SP_AltaEmpleado 'RAMSES', 'BENAVIDEZ', 'DURAN', 'Computación', '123ization@gmail.com', '04/08/1997',NULL;
EXEC SP_AltaEmpleado 'CASSANDRA', 'CEBALLOS', 'TEJADA', 'Administración de Empresas', 'tejada.cassandra12@gmail.com', '05/08/1997',NULL;
EXEC SP_AltaEmpleado 'RAUL ADRIAN', 'DOMINGUEZ', 'BADILLO', 'Computación', 'adriansilverslatter@gmail.com', '06/08/1997',NULL;
EXEC SP_AltaEmpleado 'LUIS DIEGO', 'DIAZ', 'CORTES', 'Informática', 'dieli.2131@gmail.com', '07/08/1997',NULL;
EXEC SP_AltaEmpleado 'ERICK VIRGILIO', 'DIAZ', 'FRANCO', 'Computación', 'diazf.erick@gmail.com', '08/08/1997',NULL;
EXEC SP_AltaEmpleado 'JOSE CARLOS', 'GUERRERO', 'SANCHEZ', 'Electrónica', 'jc.guesa@gmail.com', '09/08/1997',NULL;
EXEC SP_AltaEmpleado 'IRAIS', 'HERNANDEZ', 'PEREZ', 'Sistemas', '', '10/08/1997',NULL;
EXEC SP_AltaEmpleado 'JOSUE DANIEL', 'HERNANDEZ', 'SANTIAGO', 'Computación', 'danielhs.gunner@gmail.com', '11/08/1997',NULL;
EXEC SP_AltaEmpleado 'ELSA XIMENA', 'HERRERA', 'GARCIA', 'Informática', 'elxihg@gmail.com', '12/08/1997',NULL;
EXEC SP_AltaEmpleado 'SANDRA CECILIA', 'ISLAS', 'ORTEGA', 'Computación', 'sandracislas@gmail.com', '13/08/1997',NULL;
EXEC SP_AltaEmpleado 'ALEXIS GABRIEL', 'JIMENEZ', 'VILLEGAS', 'Geomatica', 'alexis.villegas.j@gmail.com', '15/03/1995',NULL;
EXEC SP_AltaEmpleado 'FRANCISCO EDER', 'MENDOZA', 'SANTOS', 'Computación', 'elite_eder30@hotmail.com', '16/03/1995',NULL;
EXEC SP_AltaEmpleado 'JOSE LEONARDO', 'OCHOA', 'NAVA', 'Computación', 'leo8aeva01@hotmail.com', '17/03/1995',NULL;
EXEC SP_AltaEmpleado 'OMAR', 'OROZCO', 'CALDERON', 'Computación', 'omar.oro.oc@gmail.com', '18/03/1995',NULL;
EXEC SP_AltaEmpleado 'MARIANO', 'ORTEGA', 'PLASCENCIA', 'Informática', 'marianosftp@gmail.com', '19/03/1995',NULL;
EXEC SP_AltaEmpleado 'ATONATIUH IVAN', 'QUIÑONES', 'VARGAS', 'Informática', 'ivanov@live.com.mx', '20/03/1995',NULL;
EXEC SP_AltaEmpleado 'JORGE NATHANIEL', 'RADILLA', 'MALDONADO', 'Mecatrónica', 'nathaniel.radilla@gmail.com', '10/10/1996',NULL;
EXEC SP_AltaEmpleado 'JULIO RAUL', 'RODRIGUEZ', 'RUIZ', 'Computación', 'super_rulaz@hotmail.com', '11/10/1996',NULL;
EXEC SP_AltaEmpleado 'MARIO ALBERTO', 'RODRIGUEZ', 'MARIN', 'Computación', 'marioa_bros@hotmail.com', '12/10/1996',NULL;
EXEC SP_AltaEmpleado 'LUIS FERNANDO', 'ROJAS', 'FLORES', 'Computación', 'lfernandorojasf@gmail.com', '25/12/1985',NULL;
EXEC SP_AltaEmpleado 'CLEMENTE DAVID', 'VALENCIA', 'ROMERO', 'Informática', 'dvidvlencia@gmail.com', '20/05/1985',NULL;
EXEC SP_AltaEmpleado 'JORGE', 'VARGAS', 'VALENCIA', 'Mecánica', '96vjrg@gmail.com', '01/01/2000',NULL;
